{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completeExceptionally"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"exception"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GraalException","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/GraalException","preciseIdentifier":"s:15DXFeedFramework14GraalExceptionO"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"platforms":["macOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Throws : GraalException. Rethrows exception from Java"}],"type":"paragraph"}]}]}]}],"sections":[],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"DXFeedFramework"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"completeExceptionally","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:15DXFeedFramework14GraalExceptionO","text":"GraalException"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"symbolKind":"method","externalID":"s:15DXFeedFramework7PromiseC21completeExceptionallyyyAA14GraalExceptionOKF","title":"completeExceptionally(_:)","role":"symbol"},"abstract":[{"text":"Completes computation exceptionally with a specified exception.","type":"text"},{"type":"text","text":" "},{"text":"This method does nothing if computation has already ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/isDone()","isActive":true},{"text":" completed,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"otherwise "},{"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/getException()","isActive":true},{"type":"text","text":" will return the specified exception."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dxfeedframework\/promise\/completeexceptionally(_:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/completeExceptionally(_:)"},"kind":"symbol","references":{"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Promise/hasException()":{"role":"symbol","abstract":[{"text":"Returns ","type":"text"},{"inlineContent":[{"text":"true","type":"text"}],"type":"strong"},{"type":"text","text":" when computation has completed exceptionally or was cancelled."},{"type":"text","text":" "},{"type":"text","text":"Use "},{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/getException()","type":"reference","isActive":true},{"text":" method to get the exceptional outcome of the computation.","type":"text"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/hasException()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasException","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","title":"hasException()","type":"topic","url":"\/documentation\/dxfeedframework\/promise\/hasexception()"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework":{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework","url":"\/documentation\/dxfeedframework","role":"collection","kind":"symbol","type":"topic","title":"DXFeedFramework","abstract":[]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Promise/complete(result:)":{"role":"symbol","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/complete(result:)","url":"\/documentation\/dxfeedframework\/promise\/complete(result:)","kind":"symbol","abstract":[{"text":"Completes computation normally with a specified result.","type":"text"},{"type":"text","text":" "},{"text":"This method does nothing if computation has already ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/isDone()","isActive":true},{"type":"text","text":" completed"},{"type":"text","text":" "},{"type":"text","text":"(normally, exceptionally, or was cancelled),"}],"title":"complete(result:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"complete"},{"kind":"text","text":"("},{"text":"result","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MarketEvent","preciseIdentifier":"s:15DXFeedFramework11MarketEventC","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Promise/completeExceptionally(_:)":{"role":"symbol","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/completeExceptionally(_:)","url":"\/documentation\/dxfeedframework\/promise\/completeexceptionally(_:)","kind":"symbol","abstract":[{"type":"text","text":"Completes computation exceptionally with a specified exception."},{"type":"text","text":" "},{"type":"text","text":"This method does nothing if computation has already "},{"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/isDone()","isActive":true},{"text":" completed,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"otherwise "},{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/getException()","type":"reference","isActive":true},{"text":" will return the specified exception.","type":"text"}],"title":"completeExceptionally(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"completeExceptionally","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:15DXFeedFramework14GraalExceptionO","text":"GraalException"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Promise/getException()":{"role":"symbol","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/getException()","url":"\/documentation\/dxfeedframework\/promise\/getexception()","kind":"symbol","abstract":[{"type":"text","text":"Returns exceptional outcome of computation. If computation has no  "},{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/hasException()","type":"reference","isActive":true},{"type":"text","text":" exception,"},{"type":"text","text":" "},{"type":"text","text":"then this method returns nil. If computation has completed exceptionally or was cancelled, then"},{"type":"text","text":" "},{"text":"the result of this method is not nil.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If computation was "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/isCancelled()"},{"type":"text","text":" cancelled, then this method returns an"},{"text":" ","type":"text"},{"type":"text","text":"instance of GraalException."}],"title":"getException()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getException"},{"text":"() -> ","kind":"text"},{"text":"GraalException","preciseIdentifier":"s:15DXFeedFramework14GraalExceptionO","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Promise/isDone()":{"role":"symbol","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/isDone()","url":"\/documentation\/dxfeedframework\/promise\/isdone()","kind":"symbol","abstract":[{"text":"Returns ","type":"text"},{"inlineContent":[{"type":"text","text":"true"}],"type":"strong"},{"type":"text","text":" when computation has"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/complete(result:)"},{"type":"text","text":" completed normally,"},{"text":" ","type":"text"},{"type":"text","text":"or "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/completeExceptionally(_:)"},{"type":"text","text":" exceptionally,"},{"text":" ","type":"text"},{"type":"text","text":"or was "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/cancel()"},{"type":"text","text":" canceled"}],"title":"isDone()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isDone","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Promise/isCancelled()":{"url":"\/documentation\/dxfeedframework\/promise\/iscancelled()","abstract":[{"type":"text","text":"Returns "},{"inlineContent":[{"type":"text","text":"true"}],"type":"strong"},{"type":"text","text":" when computation was canceled."},{"type":"text","text":" "},{"type":"text","text":"Use "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/getException()"},{"type":"text","text":" method to get the corresponding exception."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isCancelled","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/isCancelled()","role":"symbol","title":"isCancelled()"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Promise/cancel()":{"role":"symbol","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/cancel()","url":"\/documentation\/dxfeedframework\/promise\/cancel()","kind":"symbol","abstract":[{"type":"text","text":"Cancels computation. This method does nothing if computation has already "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/isDone()"},{"type":"text","text":" completed."}],"title":"cancel()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"cancel","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Promise":{"role":"symbol","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise","url":"\/documentation\/dxfeedframework\/promise","kind":"symbol","abstract":[{"text":"Result of a computation that will be completed normally or exceptionally in the future.","type":"text"},{"type":"text","text":" "},{"text":"This class is designed to represent a promise to deliver certain result.","type":"text"}],"title":"Promise","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Promise","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Promise"}],"type":"topic"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/GraalException":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"GraalException","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents errors that occur when calling graal function."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/GraalException","url":"\/documentation\/dxfeedframework\/graalexception","type":"topic","navigatorTitle":[{"text":"GraalException","kind":"identifier"}],"title":"GraalException"}}}